version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
  app:
    container_name: node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      DB_HOST: mongo:27017
volumes:
  mongodbdata:
